### ISSUE TITLE
URI encode whitespace

### ISSUE THREAD

**Issue by Robsteranium** [Swirrl/csv2rdf#47] opened 2021-01-27 13:25 UTC
If you pass a value like `"foo bar"` into a URI template, it ought to expand into `"foo%20bar"` - i.e. URI-encoding the whitespace (see e.g. [section 1.2 of the URI-template RFC](https://tools.ietf.org/html/rfc6570#section-1.2)).

At the moment this (reproducible example: [whitespace.zip](https://github.com/Swirrl/csv2rdf/files/5880421/whitespace.zip)) leads to the following exception:

```
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
13:55:59.619 [main] ERROR csv2rdf.main - #error {
 :cause Illegal character in path at index 22: http://example.net/foo bar
 :via
 [{:type java.lang.IllegalArgumentException
   :message Illegal character in path at index 22: http://example.net/foo bar
   :at [java.net.URI create URI.java 852]}
  {:type java.net.URISyntaxException
   :message Illegal character in path at index 22: http://example.net/foo bar
   :at [java.net.URI$Parser fail URI.java 2848]}]
 :trace
 [[java.net.URI$Parser fail URI.java 2848]
  [java.net.URI$Parser checkChars URI.java 3021]
  [java.net.URI$Parser parseHierarchical URI.java 3105]
  [java.net.URI$Parser parse URI.java 3053]
  [java.net.URI <init> URI.java 588]
  [java.net.URI create URI.java 850]
  [java.net.URI resolve URI.java 1036]
  [csv2rdf.util$resolve_uri invokeStatic util.clj 115]
  [csv2rdf.util$resolve_uri invoke util.clj 105]
  [csv2rdf.metadata.uri_template_property$resolve_uri_template_property invokeStatic uri_template_property.clj 23]
  [csv2rdf.metadata.uri_template_property$resolve_uri_template_property invoke uri_template_property.clj 17]
  [csv2rdf.tabular.csv$get_cell_urls invokeStatic csv.clj 138]
  [csv2rdf.tabular.csv$get_cell_urls invoke csv.clj 137]
  [csv2rdf.tabular.csv$annotate_row$fn__5873 invoke csv.clj 149]
  [clojure.core$map$fn__5587 invoke core.clj 2747]
  [clojure.lang.LazySeq sval LazySeq.java 40]
  [clojure.lang.LazySeq seq LazySeq.java 49]
  [clojure.lang.RT seq RT.java 528]
  [clojure.lang.LazilyPersistentVector create LazilyPersistentVector.java 44]
  [clojure.core$vec invokeStatic core.clj 377]
  [clojure.core$vec invoke core.clj 367]
  [csv2rdf.tabular.csv$annotate_row invokeStatic csv.clj 154]
  [csv2rdf.tabular.csv$annotate_row invoke csv.clj 143]
  [csv2rdf.tabular.csv$annotate_rows$fn__5888 invoke csv.clj 182]
  [clojure.core$map$fn__5587 invoke core.clj 2745]
  [clojure.lang.LazySeq sval LazySeq.java 40]
  [clojure.lang.LazySeq seq LazySeq.java 49]
  [clojure.lang.RT seq RT.java 528]
  [clojure.core$seq__5124 invokeStatic core.clj 137]
  [clojure.core$seq__5124 invoke core.clj 137]
  [csv2rdf.util$liberal_mapcat invokeStatic util.clj 287]
  [csv2rdf.util$liberal_mapcat invoke util.clj 284]
  [csv2rdf.csvw.minimal$fn__6050 invokeStatic minimal.clj 23]
  [csv2rdf.csvw.minimal$fn__6050 invoke minimal.clj 22]
  [clojure.lang.MultiFn invoke MultiFn.java 238]
  [csv2rdf.csvw$get_table_statements invokeStatic csvw.clj 17]
  [csv2rdf.csvw$get_table_statements invoke csvw.clj 14]
  [csv2rdf.csvw$csv__GT_rdf$fn__6771 invoke csvw.clj 33]
  [csv2rdf.util$liberal_mapcat invokeStatic util.clj 288]
  [csv2rdf.util$liberal_mapcat invoke util.clj 284]
  [csv2rdf.csvw$csv__GT_rdf invokeStatic csvw.clj 32]
  [csv2rdf.csvw$csv__GT_rdf invoke csvw.clj 19]
  [csv2rdf.csvw$csv__GT_rdf__GT_destination invokeStatic csvw.clj 42]
  [csv2rdf.csvw$csv__GT_rdf__GT_destination invoke csvw.clj 37]
  [csv2rdf.main$write_output invokeStatic main.clj 52]
  [csv2rdf.main$write_output invoke main.clj 49]
  [csv2rdf.main$_main invokeStatic main.clj 70]
  [csv2rdf.main$_main doInvoke main.clj 56]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [csv2rdf.main main nil -1]]}
```

When we would instead expect (minimal mode) output like:

```
<http://example.net/foo%20bar> <http://www.w3.org/2000/01/rdf-schema#label> "foo bar" .
```

**Comment by RickMoynihan** [comment] 2021-03-01 11:03
@lkitching presumably this will be fixed if we switch to using https://github.com/lkitching/clj-templates ?

**Comment by lkitching** [comment] 2021-03-10 12:49
@RickMoynihan - No, this was caused by some unnecessary processing in csv2rdf. The template was expanded correctly.

**Closed by lkitching** 2021-03-10 12:49 UTC
Labels: bug
