### ISSUE TITLE
NoSuchFieldError bug when importing table2qb in muttnik deps

### ISSUE THREAD

**Issue by jennet** [Swirrl/csv2rdf#36] opened 2020-02-06 14:11 UTC
Added table2qb in muttnik deps, calling it from a simple clojure function results in:
```
Syntax error (NoSuchFieldError) compiling at (mut/cube_builder.clj:64:1).
JAVA_ISO_CONTROL
```

Seems to be a problem in CSV2RDF uri template usage?

```
Syntax error (NoSuchFieldError) compiling at (mut/cube_builder.clj:64:1).
JAVA_ISO_CONTROL
user=> *e
#error {
 :cause "JAVA_ISO_CONTROL"
 :via
 [{:type clojure.lang.Compiler$CompilerException
   :message "Syntax error compiling at (mut/cube_builder.clj:64:1)."
   :data #:clojure.error{:phase :compile-syntax-check, :line 64, :column 1, :source "mut/cube_builder.clj"}
   :at [clojure.lang.Compiler load "Compiler.java" 7648]}
  {:type java.lang.NoSuchFieldError
   :message "JAVA_ISO_CONTROL"
   :at [com.github.fge.uritemplate.parse.CharMatchers <clinit> "CharMatchers.java" 40]}]
 :trace
 [[com.github.fge.uritemplate.parse.CharMatchers <clinit> "CharMatchers.java" 40]
  [com.github.fge.uritemplate.parse.VariableSpecParser <clinit> "VariableSpecParser.java" 44]
  [sun.reflect.NativeMethodAccessorImpl invoke0 "NativeMethodAccessorImpl.java" -2]
  [sun.reflect.NativeMethodAccessorImpl invoke "NativeMethodAccessorImpl.java" 62]
  [sun.reflect.DelegatingMethodAccessorImpl invoke "DelegatingMethodAccessorImpl.java" 43]
  [java.lang.reflect.Method invoke "Method.java" 498]
  [csv2rdf.util$invoke_method invokeStatic "util.clj" 75]
  [csv2rdf.util$invoke_method invoke "util.clj" 69]
  [csv2rdf.util$invoke_method invokeStatic "util.clj" 72]
  [csv2rdf.util$invoke_method invoke "util.clj" 69]
  [csv2rdf.metadata.column$parse_uri_template_variable invokeStatic "column.clj" 26]
  [csv2rdf.metadata.column$parse_uri_template_variable invoke "column.clj" 25]
  [csv2rdf.metadata.column$uri_template_variable invokeStatic "column.clj" 30]
  [csv2rdf.metadata.column$uri_template_variable invoke "column.clj" 28]
  [csv2rdf.metadata.column$validate_column_name invokeStatic "column.clj" 41]
  [csv2rdf.metadata.column$validate_column_name invoke "column.clj" 38]
  [csv2rdf.metadata.validator$chain$fn__8201$fn__8202 invoke "validator.clj" 99]
  [csv2rdf.metadata.validator$optional_key$fn__8228 invoke "validator.clj" 166]
  [csv2rdf.metadata.validator$kvps$fn__8233$fn__8234 invoke "validator.clj" 184]
  [clojure.core$map$fn__5866 invoke "core.clj" 2755]
  [clojure.lang.LazySeq sval "LazySeq.java" 42]
  [clojure.lang.LazySeq seq "LazySeq.java" 51]
  [clojure.lang.RT seq "RT.java" 535]
  [clojure.core$seq__5402 invokeStatic "core.clj" 137]
  [clojure.core$filter$fn__5893 invoke "core.clj" 2809]
  [clojure.lang.LazySeq sval "LazySeq.java" 42]
  [clojure.lang.LazySeq seq "LazySeq.java" 51]
  [clojure.lang.Cons next "Cons.java" 39]
  [clojure.lang.RT next "RT.java" 713]
  [clojure.core$next__5386 invokeStatic "core.clj" 64]
  [clojure.core.protocols$fn__8159 invokeStatic "protocols.clj" 169]
  [clojure.core.protocols$fn__8159 invoke "protocols.clj" 124]
  [clojure.core.protocols$fn__8114$G__8109__8123 invoke "protocols.clj" 19]
  [clojure.core.protocols$seq_reduce invokeStatic "protocols.clj" 31]
  [clojure.core.protocols$fn__8146 invokeStatic "protocols.clj" 75]
  [clojure.core.protocols$fn__8146 invoke "protocols.clj" 75]
  [clojure.core.protocols$fn__8088$G__8083__8101 invoke "protocols.clj" 13]
  [clojure.core$reduce invokeStatic "core.clj" 6828]
  [clojure.core$into invokeStatic "core.clj" 6895]
  [clojure.core$into invoke "core.clj" 6887]
  [csv2rdf.metadata.validator$kvps$fn__8233 invoke "validator.clj" 186]
  [csv2rdf.metadata.types$validate_object_of$fn__8442 invoke "types.clj" 293]
  [csv2rdf.metadata.validator$variant$v__8207 invoke "validator.clj" 120]
  [csv2rdf.metadata.validator$variant$v__8207 invoke "validator.clj" 117]
  [csv2rdf.metadata.validator$array_of$fn__8211$fn__8212 invoke "validator.clj" 130]
  [clojure.core$map_indexed$mapi__8548$fn__8549 invoke "core.clj" 7308]
  [clojure.lang.LazySeq sval "LazySeq.java" 42]
  [clojure.lang.LazySeq seq "LazySeq.java" 51]
  [clojure.lang.RT seq "RT.java" 535]
  [clojure.core$seq__5402 invokeStatic "core.clj" 137]
  [clojure.core$filter$fn__5893 invoke "core.clj" 2809]
  [clojure.lang.LazySeq sval "LazySeq.java" 42]
  [clojure.lang.LazySeq seq "LazySeq.java" 51]
  [clojure.lang.RT seq "RT.java" 535]
  [clojure.lang.LazilyPersistentVector create "LazilyPersistentVector.java" 44]
  [clojure.core$vec invokeStatic "core.clj" 377]
  [clojure.core$vec invoke "core.clj" 367]
  [csv2rdf.metadata.validator$array_of$fn__8211 invoke "validator.clj" 129]
  [csv2rdf.metadata.column$columns invokeStatic "column.clj" 98]
  [csv2rdf.metadata.column$columns invoke "column.clj" 97]
  [csv2rdf.metadata.validator$optional_key$fn__8228 invoke "validator.clj" 166]
  [csv2rdf.metadata.validator$kvps$fn__8233$fn__8234 invoke "validator.clj" 184]
  [clojure.core$map$fn__5866 invoke "core.clj" 2755]
  [clojure.lang.LazySeq sval "LazySeq.java" 42]
  [clojure.lang.LazySeq seq "LazySeq.java" 51]
  [clojure.lang.RT seq "RT.java" 535]
  [clojure.core$seq__5402 invokeStatic "core.clj" 137]
  [clojure.core$filter$fn__5893 invoke "core.clj" 2809]
  [clojure.lang.LazySeq sval "LazySeq.java" 42]
  [clojure.lang.LazySeq seq "LazySeq.java" 51]
  [clojure.lang.Cons next "Cons.java" 39]
  [clojure.lang.RT next "RT.java" 713]
  [clojure.core$next__5386 invokeStatic "core.clj" 64]
  [clojure.core.protocols$fn__8159 invokeStatic "protocols.clj" 169]
  [clojure.core.protocols$fn__8159 invoke "protocols.clj" 124]
  [clojure.core.protocols$fn__8114$G__8109__8123 invoke "protocols.clj" 19]
  [clojure.core.protocols$seq_reduce invokeStatic "protocols.clj" 31]
  [clojure.core.protocols$fn__8146 invokeStatic "protocols.clj" 75]
  [clojure.core.protocols$fn__8146 invoke "protocols.clj" 75]
  [clojure.core.protocols$fn__8088$G__8083__8101 invoke "protocols.clj" 13]
  [clojure.core$reduce invokeStatic "core.clj" 6828]
  [clojure.core$into invokeStatic "core.clj" 6895]
  [clojure.core$into invoke "core.clj" 6887]
  [csv2rdf.metadata.validator$kvps$fn__8233 invoke "validator.clj" 186]
  [csv2rdf.metadata.types$validate_object_of$fn__8442 invoke "types.clj" 293]
  [csv2rdf.metadata.validator$variant$v__8207 invoke "validator.clj" 120]
  [csv2rdf.metadata.validator$variant$v__8207 invoke "validator.clj" 117]
  [csv2rdf.metadata.schema$schema invokeStatic "schema.clj" 98]
  [csv2rdf.metadata.schema$schema invoke "schema.clj" 97]
  [csv2rdf.metadata.validator$variant$v__8207 invoke "validator.clj" 120]
  [csv2rdf.metadata.validator$variant$v__8207 invoke "validator.clj" 117]
  [csv2rdf.metadata.validator$optional_key$fn__8228 invoke "validator.clj" 166]
  [csv2rdf.metadata.validator$kvps$fn__8233$fn__8234 invoke "validator.clj" 184]
  [clojure.core$map$fn__5866 invoke "core.clj" 2755]
  [clojure.lang.LazySeq sval "LazySeq.java" 42]
  [clojure.lang.LazySeq seq "LazySeq.java" 51]
  [clojure.lang.RT seq "RT.java" 535]
  [clojure.core$seq__5402 invokeStatic "core.clj" 137]
  [clojure.core$filter$fn__5893 invoke "core.clj" 2809]
  [clojure.lang.LazySeq sval "LazySeq.java" 42]
  [clojure.lang.LazySeq seq "LazySeq.java" 51]
  [clojure.lang.Cons next "Cons.java" 39]
  [clojure.lang.RT next "RT.java" 713]
  [clojure.core$next__5386 invokeStatic "core.clj" 64]
  [clojure.core.protocols$fn__8159 invokeStatic "protocols.clj" 169]
  [clojure.core.protocols$fn__8159 invoke "protocols.clj" 124]
  [clojure.core.protocols$fn__8114$G__8109__8123 invoke "protocols.clj" 19]
  [clojure.core.protocols$seq_reduce invokeStatic "protocols.clj" 31]
  [clojure.core.protocols$fn__8146 invokeStatic "protocols.clj" 75]
  [clojure.core.protocols$fn__8146 invoke "protocols.clj" 75]
  [clojure.core.protocols$fn__8088$G__8083__8101 invoke "protocols.clj" 13]
  [clojure.core$reduce invokeStatic "core.clj" 6828]
  [clojure.core$into invokeStatic "core.clj" 6895]
  [clojure.core$into invoke "core.clj" 6887]
  [csv2rdf.metadata.validator$kvps$fn__8233 invoke "validator.clj" 186]
  [csv2rdf.metadata.types$validate_object_of$fn__8442 invoke "types.clj" 293]
  [csv2rdf.metadata.validator$variant$v__8207 invoke "validator.clj" 120]
  [csv2rdf.metadata.validator$variant$v__8207 invoke "validator.clj" 117]
  [csv2rdf.metadata.types$validate_contextual_object$fn__8469 invoke "types.clj" 373]
  [csv2rdf.metadata.validator$variant$v__8207 invoke "validator.clj" 120]
  [csv2rdf.metadata.validator$variant$v__8207 invoke "validator.clj" 117]
  [csv2rdf.metadata.table$parse_table_json invokeStatic "table.clj" 38]
  [csv2rdf.metadata.table$parse_table_json invoke "table.clj" 37]
  [csv2rdf.metadata$parse_metadata_json invokeStatic "metadata.clj" 17]
  [csv2rdf.metadata$parse_metadata_json invoke "metadata.clj" 10]
  [csv2rdf.metadata$parse_table_group_from_source invokeStatic "metadata.clj" 23]
  [csv2rdf.metadata$parse_table_group_from_source invoke "metadata.clj" 21]
  [csv2rdf.tabular.processing$get_metadata invokeStatic "processing.clj" 26]
  [csv2rdf.tabular.processing$get_metadata invoke "processing.clj" 20]
  [csv2rdf.csvw$csv__GT_rdf invokeStatic "csvw.clj" 28]
  [csv2rdf.csvw$csv__GT_rdf invoke "csvw.clj" 19]
  [table2qb.pipelines.codelist$codelist__GT_csvw__GT_rdf invokeStatic "codelist.clj" 106]
  [table2qb.pipelines.codelist$codelist__GT_csvw__GT_rdf invoke "codelist.clj" 101]
  [table2qb.pipelines.codelist$codelist_pipeline invokeStatic "codelist.clj" 113]
  [table2qb.pipelines.codelist$codelist_pipeline invoke "codelist.clj" 108]
  [clojure.lang.AFn applyToHelper "AFn.java" 165]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.Var applyTo "Var.java" 705]
  [clojure.core$apply invokeStatic "core.clj" 665]
  [clojure.core$apply invoke "core.clj" 660]
  [table2qb.cli.tasks$exec_pipeline$fn__7531 invoke "tasks.clj" 192]
  [table2qb.cli.tasks$exec_pipeline invokeStatic "tasks.clj" 187]
  [table2qb.cli.tasks$exec_pipeline invoke "tasks.clj" 184]
  [table2qb.cli.tasks$eval7540$fn__7542 invoke "tasks.clj" 217]
  [clojure.lang.MultiFn invoke "MultiFn.java" 239]
  [table2qb.main$inner_main invokeStatic "main.clj" 26]
  [table2qb.main$inner_main invoke "main.clj" 18]
  [mut.cube_builder$generate_all_cubes invokeStatic "cube_builder.clj" 58]
  [mut.cube_builder$generate_all_cubes invoke "cube_builder.clj" 49]
  [mut.cube_builder$eval7588 invokeStatic "cube_builder.clj" 64]
  [mut.cube_builder$eval7588 invoke "cube_builder.clj" 64]
  [clojure.lang.Compiler eval "Compiler.java" 7177]
  [clojure.lang.Compiler load "Compiler.java" 7636]
  [clojure.lang.RT loadResourceScript "RT.java" 381]
  [clojure.lang.RT loadResourceScript "RT.java" 372]
  [clojure.lang.RT load "RT.java" 459]
  [clojure.lang.RT load "RT.java" 424]
  [clojure.core$load$fn__6839 invoke "core.clj" 6126]
  [clojure.core$load invokeStatic "core.clj" 6125]
  [clojure.core$load doInvoke "core.clj" 6109]
  [clojure.lang.RestFn invoke "RestFn.java" 408]
  [clojure.core$load_one invokeStatic "core.clj" 5908]
  [clojure.core$load_one invoke "core.clj" 5903]
  [clojure.core$load_lib$fn__6780 invoke "core.clj" 5948]
  [clojure.core$load_lib invokeStatic "core.clj" 5947]
  [clojure.core$load_lib doInvoke "core.clj" 5928]
  [clojure.lang.RestFn applyTo "RestFn.java" 142]
  [clojure.core$apply invokeStatic "core.clj" 667]
  [clojure.core$load_libs invokeStatic "core.clj" 5985]
  [clojure.core$load_libs doInvoke "core.clj" 5969]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invokeStatic "core.clj" 667]
  [clojure.core$require invokeStatic "core.clj" 6007]
  [clojure.core$require doInvoke "core.clj" 6007]
  [clojure.lang.RestFn invoke "RestFn.java" 408]
  [user$eval148 invokeStatic "NO_SOURCE_FILE" 1]
  [user$eval148 invoke "NO_SOURCE_FILE" 1]
  [clojure.lang.Compiler eval "Compiler.java" 7177]
  [clojure.lang.Compiler eval "Compiler.java" 7132]
  [clojure.core$eval invokeStatic "core.clj" 3214]
  [clojure.core$eval invoke "core.clj" 3210]
  [clojure.main$repl$read_eval_print__9086$fn__9089 invoke "main.clj" 437]
  [clojure.main$repl$read_eval_print__9086 invoke "main.clj" 437]
  [clojure.main$repl$fn__9095 invoke "main.clj" 458]
  [clojure.main$repl invokeStatic "main.clj" 458]
  [clojure.main$repl_opt invokeStatic "main.clj" 522]
  [clojure.main$main invokeStatic "main.clj" 667]
  [clojure.main$main doInvoke "main.clj" 616]
  [clojure.lang.RestFn invoke "RestFn.java" 397]
  [clojure.lang.AFn applyToHelper "AFn.java" 152]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.lang.Var applyTo "Var.java" 705]
  [clojure.main main "main.java" 40]]}
```

**Comment by lkitching** [comment] 2020-03-03 16:34
This was caused by conflicting versions of guava when importing `csv2rdf` into another project. Fixed by 88ee85721ef9aace9fd0659066f6b57ee1cc36ff which uses a newer version of the URI templates library which does not depend on the removed classes.

**Closed by lkitching** 2020-03-03 16:34 UTC
